apiVersion: apps/v1
kind: Deployment
metadata:
  name: umso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umso
  template:
    metadata:
      labels:
        app: umso
    spec:
      containers:
        - name: umso
          image: umso:local
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: umso
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: umso
  type: NodePort